### ISSUE TITLE
我又尝试了下，这样是什么问题？大神

### ISSUE THREAD

**Issue by yjlw** [renrenio/renren-fast-vue#55]
我cnpm install后本地能跑,node_moudles也有包，但是很诡异的是有的文件夹带有快捷方式的图标，我把整node_moudules复制出去果然只要带有快捷方式的文件夹里面文件全部没有，这是怎么回事？我原先想在cnpm install一下然后把整个node_mouduls文件夹全部发送过去，这下快捷方式的文件夹里面是空的，我的项目里又有。。。。。求解答下。。。。

**Comment by daxiongYang** [comment]
cnpm安装生成的文件具体是怎样，本人也不懂。
至于你说存在的快捷方式文件夹，你将自己本地文件的快捷方式文件夹拷贝给其他同事电脑，你觉得这样能拷贝吗？
在他电脑上重新安装一下不就行了？
