### ISSUE TITLE
点击动态加载的菜单后提示Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by lmasdata** [renrenio/renren-fast-vue#66]
你好，我从接口获取数据后使用route['component'] = () => import('@/views/processdesign/flowapptz')拼接组件然后动态挂载到路由上，点击后菜单提示Failed to mount component: template or render function not defined.
请问这种加载组件的方式不对么

**Comment by daxiongYang** [comment]
如果是用循环遍历拼接组件路径字符串的，请尝试将遍历下标用闭包处理let i = 0; 定义 或者(function(i) {})(i);处理下。

**Comment by lmasdata** [comment]
谢谢，已解决，是因为VUE的编译原因导致的
