### ISSUE TITLE
table-tree-column 删除子节点时要需要把_expanded 设置为false

### ISSUE THREAD

**Issue by linxyruffy** [renrenio/renren-fast-vue#67]
// 移除子节点
    removeChildNode(data, parentId) {
      var parentIds = isArray(parentId) ? parentId : [parentId]
      if (parentId.length <= 0) {
        return data
      }
      var ids = []
      for (var i = 0; i < data.length; i++) {
        if (parentIds.indexOf(data[i][this.parentKey]) !== -1 && parentIds.indexOf(data[i][this.treeKey]) === -1) {
          data[i]._expanded = false;
          ids.push(data.splice(i, 1)[0][this.treeKey])
          i--
        }
      }
      return this.removeChildNode(data, ids)
    }

**Comment by daxiongYang** [comment]
https://github.com/renrenio/renren-fast-vue/commit/63bf7355bd2b1c7072d5660608b75e8d8f819ab5
