### ISSUE TITLE
在vue项目中　请求另一个项目接口地址报错Error: Network Error

### ISSUE THREAD

**Issue by lijian69017436** [renrenio/renren-fast-vue#73]
Access to XMLHttpRequest at 'http://localhost:8181/ekIntegralProduct/pu/list?t=1547010263735&page=1&limit=10&key=' from origin 'http://localhost:8001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
createError.js?c712:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js?c712:16)
    at XMLHttpRequest.handleError (xhr.js?0730:87)

**Comment by lijian69017436** [comment]
这个是vue项目配置问题吗?   我另一个项目接口 是已经解决跨域问题的呢

**Comment by daxiongYang** [comment]
这是跨域问题，请搜索相应文章解决。
