### ISSUE TITLE
如果关闭代理之后，请求百度的http://api.map.baidu.com/geocoder接口会出现以下问题。

### ISSUE THREAD

**Issue by liwanlivip** [renrenio/renren-fast-vue#74]
如果关闭代理之后，请求百度的http://api.map.baidu.com/geocoder接口会出现以下问题。
![menu saveimg savepath20190215161938](https://user-images.githubusercontent.com/37563099/52843564-7491f780-313d-11e9-9fff-317bb28142a2.jpg)

![menu saveimg savepath20190215161531](https://user-images.githubusercontent.com/37563099/52843461-27ae2100-313d-11e9-904f-eade29d1c04a.jpg)

![menu saveimg savepath20190215162047](https://user-images.githubusercontent.com/37563099/52843645-aefb9480-313d-11e9-8661-015c58cc095a.jpg)

**Comment by daxiongYang** [comment]
这是跨域问题，请搜索相应文章解决。
