### ISSUE TITLE
验证码页面加载不出来

### ISSUE THREAD

**Issue by penghuizhang** [renrenio/renren-fast-vue#75]
经过查看
部署端口  I  Your application is running here: http://localhost:8001 
![image](https://user-images.githubusercontent.com/17181083/53286069-cc66d900-37a3-11e9-86a2-a06324c828e9.png)

但是这个验证码请求地址端口是8080 怎么加载验证码？
![image](https://user-images.githubusercontent.com/17181083/53286056-afcaa100-37a3-11e9-8164-60d86cc53b85.png)

**Comment by daxiongYang** [comment]
请正常启动运行后台，并保证localhost:8080/renren-fast能正常请求访问后台项目。

**Comment by chvrches625** [comment]
后台配置必须得是8080端口，我也被这个坑了，不然加载不出验证码。
