### ISSUE TITLE
求助：安装依赖报错，启动页面报错

### ISSUE THREAD

**Issue by AnnieYoung** [renrenio/renren-fast-vue#80]
npm install 各种报错，后来重新用cnpm安装不报错了，但是 run dev只有一句
![image](https://user-images.githubusercontent.com/32160859/55307026-c346e700-5488-11e9-9ade-41abc7b78211.png)；
后来都没办法启动起来了，报错如下
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! renren-fast-vue@1.2.2 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js` `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the renren-fast-vue@1.2.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ps：不明原因 只要一用vscode打开项目文件夹 内存瞬间99%被吃掉了，cpu温度70+，

**Comment by guoz185013** [comment]
解决了吗
我的问题跟你的一模一样

**Comment by AnnieYoung** [comment]
解决了  具体的不记得了 可能是重新下载了一个新的zip然后在cnpm install 就好了

但是 内存99%那个还是无解 又一次cpu温度都85了。。。
