### ISSUE TITLE
timeout of 30000ms exceeded 请求菜单列表和权限失败，跳转至登录页！！

### ISSUE THREAD

**Issue by Loofer** [renrenio/renren-fast-vue#82]
打包放入nginx，每次开机重启后，刚开始登录都会登录不了。

**Comment by Loofer** [comment]
/sys/menu/nav?t=1554131674032 axios Provisional headers are shown

**Comment by Loofer** [comment]
/sys/menu/nav 这边查看到的原因是这个接口请求后台没请求到
报错
Provisional headers are shown

**Comment by Loofer** [comment]
启动参数加 -Djava.security.egd=file:/dev/./urandom 就可以了，原因是密码加密用了 SHA-1

**Comment by jacksparrow414** [comment]
你好，这个启动参数是在哪里加呢？我切换到开发环境下，启动提示如下，请问有解决办法吗？
<img width="1087" alt="屏幕快照 2019-04-05 上午10 42 50" src="https://user-images.githubusercontent.com/33389378/55600664-98fa6f80-578f-11e9-80c0-637e2bf10e58.png">

**Comment by Loofer** [comment]
> 你好，这个启动参数是在哪里加呢？我切换到开发环境下，启动提示如下，请问有解决办法吗？
> <img alt="屏幕快照 2019-04-05 上午10 42 50" width="1087" src="https://user-images.githubusercontent.com/33389378/55600664-98fa6f80-578f-11e9-80c0-637e2bf10e58.png">
启动参数是 java -jar 的时候加的，生成环境加的
