### ISSUE TITLE
访问系统设置时候出现Error: Cannot find module './modules/modules/sys/user.html.vue'.

### ISSUE THREAD

**Issue by SkyBlueWhite** [renrenio/renren-fast-vue#88]
![image](https://user-images.githubusercontent.com/35592194/60413738-7bab3500-9c08-11e9-8a53-755e08f3dfcf.png)
可以正常登陆，访问系统设置菜单时出错

**Comment by kkwwang** [comment]
菜单地址配置有误
 




------------------ Original ------------------

**Comment by kkwwang** [comment]
菜单地址配置有误

**Comment by SkyBlueWhite** [comment]
tks 更新了一次菜单数据后解决了

**Comment by SkyBlueWhite** [comment]
更新了菜单数据后可以正常访问，谢谢
