### ISSUE TITLE
最新包下载的依赖需要python2？

### ISSUE THREAD

**Issue by fusxAbc** [renrenio/renren-fast-vue#95]
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:13:12)
gyp verb `which` failed     at F (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:68:19)
gyp verb `which` failed     at E (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:80:29)
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:89:16
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:13:12)
gyp verb `which` failed     at F (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:68:19)
gyp verb `which` failed     at E (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:80:29)
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:89:16
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:89:16\n' +
gyp verb `which` failed     '    at E:\\workspace_vue\\renren-fast-vue\\node_modules\\_isexe@2.0.0@isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at E:\\workspace_vue\\renren-fast-vue\\node_modules\\_isexe@2.0.0@isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:13:12)
gyp verb `which` failed     at F (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:68:19)
gyp verb `which` failed     at E (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:80:29)
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:89:16
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:13:12)
gyp verb `which` failed     at F (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:68:19)
gyp verb `which` failed     at E (E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:80:29)
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_which@1.3.1@which\which.js:89:16
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at E:\workspace_vue\renren-fast-vue\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at E:\\workspace_vue\\renren-fast-vue\\node_modules\\_which@1.3.1@which\\which.js:89:16\n' +
gyp verb `which` failed     '    at E:\\workspace_vue\\renren-fast-vue\\node_modules\\_isexe@2.0.0@isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at E:\\workspace_vue\\renren-fast-vue\\node_modules\\_isexe@2.0.0@isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\workspace_vue\renren-fast-vue\node_modules\_node-gyp@3.8.0@node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\workspace_vue\renren-fast-vue\node_modules\_node-gyp@3.8.0@node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (E:\workspace_vue\renren-fast-vue\node_modules\_graceful-fs@4.2.3@graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "E:\\workspace_vue\\renren-fast-vue\\node_modules\\_node-gyp@3.8.0@node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\workspace_vue\renren-fast-vue\node_modules\_node-sass@4.9.0@node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
[npminstall:runscript:error] node-sass@4.9.0 scripts.postinstall run "node scripts/build.js" error: Error [RunScriptError]: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js" error, exit code 1
    at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  name: 'RunScriptError',
  stdio: [Object]
}
× Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js" error, exit code 1
RunScriptError: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js" error, exit code 1
    at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by fusxAbc** [comment]
已解决

**Comment by zyd** [comment]
我也遇到了，你是怎么解决的？

**Comment by xshi0001** [comment]
python2?

我本地是python3, 这个怎么

gyp verb `which` succeeded python C:\Users\xshi0\AppData\Local\Programs\Python\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\xshi0\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "E:\\nodejs\\node-v12.13.0-win-x64\\node.exe" "D:\\WorkPlace\\renren\\renren-fast-vue\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass
_library="
gyp ERR! cwd D:\WorkPlace\renren\renren-fast-vue\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xshi0\AppData\Roaming\npm-cache\_logs\2020-06-19T11_08_48_795Z-debug.log
